version: "3.9"

services:
  splunk:
    image: splunk/splunk:latest
    container_name: splunk_siem
    environment:
      SPLUNK_GENERAL_TERMS: "--accept-sgt-current-at-splunk-com"
      SPLUNK_START_ARGS: "--accept-license"
      SPLUNK_PASSWORD: "StrongPassword123!" # Replace with a secure password
      SPLUNK_ENABLE_LISTEN: "9997"
    ports:
      - "8000:8000"
      - "9997:9997"
      - "8089:8089"
    restart: unless-stopped