[install]
build = 252053444
is_configured = 0
state = enabled
[launcher]
author = Splunk Inc.
description = Splunk Secure Gateway
version = 3.10.12
[package]
check_for_updates = false
[triggers]
reload.passwords = simple
reload.securegateway = simple
[ui]
is_visible = 1
label = Splunk Secure Gateway

